
version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: ac-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    restart: unless-stopped
    volumes:
      - db:/data/db
  spring:
    depends_on:
      - mongodb
    # build: ../ash-spring
    image: edelacr1/ash-spring:latest
    container_name: ac-spring
    env_file: ./.env
    ports:
      - $SPRING_MAIL_LOCAL_PORT:$SPRING_MAIL_DOCKER_PORT
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  ng:
    # build: ../ash-ng
    image: edelacr1/ash-ng:latest
    container_name: ac-ng
    ports:
      - $NG_LOCAL_PORT:$NG_DOCKER_PORT
      - $SSL_LOCAL_PORT:$SSL_DOCKER_PORT
    depends_on:
      - spring
    restart: on-failure
    volumes:    
      - /nfs/ashpi/nginx/www/:/var/www/
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  db:
