# version: '3'
# services:
# #************Mongo DB***************
#   database_mongo:
#     container_name: mongo_container
#     image: mongo:latest
#     environment:
#     - MONGO_INITDB_ROOT_DATABASE=asmd_mongo_db
#     volumes:
#     - ./mongodb_data_container:/data/db
#     #means you want to set data on container persist on your local folder named mongo-volume . /data/db/ is a folder that already created inside the mongo container.
#     ports:
#     - 27017:27017
#     networks:
#     - asmd_net
#   #************Backend***************
#   backend_spring:
#     container_name: spring_container
#     build: ../springboot-auth-service/Dockerfile
#     ports:
#         - 8080:8080
#     depends_on:
#         - database_mongo
#     networks:
#         - asmd_net
# networks:
#   asmd_net:
#     driver: bridge

version: "3.8"

services:
  mongo_db:
    image: mongo:6.0.12
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongo_db
    build: ../springboot-auth-service
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $SPRING_MAIL_LOCAL_PORT:$SPRING_MAIL_DOCKER_PORT
    environment:
      # Original
      # SPRING_APPLICATION_JSON: '{
      #     "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
      #   }'
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@cluster95314.rtpsl7b.mongodb.net/"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: