
version: "3.8"
services:
  spring:
    # build: ../ash-spring
    image: edelacr1/ash-spring:latest
    container_name: ac-spring
    environment:
      - TZ=America/New_York
    env_file: ./.env
    ports:
      - $SPRING_MAIL_LOCAL_PORT:$SPRING_MAIL_DOCKER_PORT
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  ng:
    # build: ../ash-ng
    image: edelacr1/ash-ng:latest
    container_name: ac-ng
    environment:
      - TZ=America/New_York
    ports:
      - $NG_LOCAL_PORT:$NG_DOCKER_PORT
      - $SSL_LOCAL_PORT:$SSL_DOCKER_PORT
    depends_on:
      - spring
    restart: on-failure
    volumes:    
      - $NGINX_LOCAL_DIR:$NGINX_DOCKER_DIR
      - $SSL_LOCAL_DIR:$SSL_DOCKER_DIR
